title: "My Portfolio"
description: "A simple personal portfolio built with GitHub Pages"
#theme: jekyll-theme-cayman # You can choose other GitHub Pages themes here
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: "" # Leave empty unless the site is hosted in a subdirectory
url: "https://mavito.github.io" # Replace with your GitHub Pages URL

# Social media links
social_links:
  github: "https://github.com/mavito"
  linkedin: "https://linkedin.com/in/manas-tokale"

# Navigation bar items
nav:
  - title: "About"
    url: "#about"
  - title: "Projects"
    url: "#projects"
  - title: "Contact"
    url: "#contact"
