title: My Portfolio
description: A showcase of my projects and experience.
#theme: jekyll-theme-cayman  # You can replace this with any other GitHub Pages supported theme.

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Add this to include your custom stylesheet
include:
  - style.css

# Add the stylesheet to the head of your site
markdown_css: style.css

navbar:
  - name: Home
    link: /
  - name: About
    link: /about.md  # Links to the new about page
  - name: Projects
    link: /projects.md  # Links to the projects section in README.md
